name: PHP Composer

on:
  push:
  pull_request:

jobs:
  build:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug
        extensions: dom, simplexml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install

    - name: Run PHPStan
      run: composer run phpstan

    - name: Run test suite
      run: composer run phpunit

    - name: Run PHPInfection
      run: composer run infection
