name: PHP code quality

on:
  push:
  pull_request:

jobs:
  static:
    name: Static code analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer
        extensions: dom, simplexml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install

    - name: Run PHPStan
      run: composer run phpstan

  test:
    name: Tests on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4']

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: xdebug
        extensions: dom, simplexml

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: composer install
      run: composer install

    - name: Run test suite
      run: composer run phpunit

    - name: Run PHPInfection
      if: ${{ matrix.php != '7.3' }}
      run: composer run infection
